version: "3"
services:
  postgres:
    image: postgres:13
    restart: always
    container_name: postgres
    hostname: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
    networks:
      - proxy
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SESSION_SECRET=${SESSION_SECRET}
      - PORT=${PORT}
      - CORS_ORIGIN=${CORS_ORIGIN}
    volumes:
      - /app/node_modules
      - ./backend/config:/app/config
      - ./backend/src:/app/src
      - ./backend/test:/app/test
    networks:
      - proxy
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./frontend:/app
    networks:
      - proxy

networks:
  proxy:
    external: true
