version: '3'
services:
  postgres:
    image: postgres:13
    restart: always
    container_name: postgres
    hostname: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SESSION_SECRET=${SESSION_SECRET}
      - PORT=${PORT}
    volumes:
      - /app/node_modules
      - ./backend/config:/app/config
      - ./backend/src:/app/src
      - ./backend/test:/app/test
    ports:
      - "3000:3000"
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./frontend:/app
    ports:
      - "8080:8080"