version: '3'
services:
  postgres:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=boiler_js
      - POSTGRES_PASSWORD=plate_js
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
volumes:
  postgres: